### ISSUE TITLE
[Feature]:Want a function to query colleciont id by collection name

### ISSUE THREAD

**Issue by elstic** [milvus-io/birdwatcher#119]
### Is your feature request related to a problem? Please describe.

When there are a lot of collections, I want to see the details of a collection by a collection name I know. Now I need to "show collections" and look for them one by one.

https://user-images.githubusercontent.com/48523564/227472975-25a666d8-03d9-4f23-8659-5746019557ff.mov

**Comment by congqixia** [comment]
Fixed by #120
