### ISSUE TITLE
[Feature]: Command history

### ISSUE THREAD

**Issue by yah01** [milvus-io/birdwatcher#121]
### Is your feature request related to a problem? Please describe.

I can't re-run command just by traveling through the history

### Describe the solution you'd like.

![image](https://user-images.githubusercontent.com/12216890/227490056-afdab93c-ccc6-4522-8162-bd4edc64d9b6.png)
hint based on history

and

![image](https://user-images.githubusercontent.com/12216890/227490774-5249bb05-b3c4-4135-a503-fbe32fd4c55f.png)

**Comment by congqixia** [comment]
Close as completed
