### ISSUE TITLE
[Bug]: "birdwatcher --version" and "birdwatcher version" doesn't print the version info

### ISSUE THREAD

**Issue by yah01** [milvus-io/birdwatcher#124]
### Current Behavior

As I typed "birdwatcher --version" and "birdwatcher version", they both start the interactive mode:
![image](https://user-images.githubusercontent.com/12216890/227828660-36b9a799-9053-4f7a-9538-2263797a6d78.png)
And no way to print the version, even in the interactive mode:
![image](https://user-images.githubusercontent.com/12216890/227828704-d968a423-11d8-48c1-9013-958b108de7d4.png)

### Expected Behavior

Only print the version with the two commands

**Comment by zhuwenxing** [comment]
/assign

This can be solved by goreleaser

**Comment by congqixia** [comment]
@zhuwenxing Added some basic function to print dev version. It would be nice for `goreleaser` to replace the Release Version automatically
