### ISSUE TITLE
[Enhancement]: Add field-level `show segment-index ` conditional filtering 

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/birdwatcher#294]
### What would you like to be added?

<img width="1134" alt="截屏2024-08-13 21 15 13" src="https://github.com/user-attachments/assets/9c74ea4b-6d87-43da-8a95-b443ecf0a58b">

**Comment by congqixia** [comment]
@wangting0128 in latest v1.0.x `show segment-index` support `--collection` & `--segment` filter. Are there any other filter needed for this case?

**Comment by wangting0128** [comment]
> @wangting0128 in latest v1.0.x `show segment-index` support `--collection` & `--segment` filter. Are there any other filter needed for this case?

Want to filter only the segment-index information of a certain field in the collection :>

**Comment by wangting0128** [comment]
Great!
