### ISSUE TITLE
[Bug]: Due to the use of unsafe.Pointer, getting security Vulnerability in scan

### ISSUE THREAD

**Issue by pkk0909** [milvus-io/birdwatcher#314]
### Current Behavior

Due to the use of unsafe.Pointer in GetUnexportedField function (bapps/[go_prompt_parser.go file], getting critical vulnerability in static code scan. Need to avoid the use of unsafe.Pointer in code base

### Expected Behavior

unsafe.Pointer need to be removed from the code base so that git repo will not have any  security vulnerability in repo static code scan.

### Steps To Reproduce

```markdown
N/A
```

### Environment

```markdown
code scan issue
```

**Comment by pkk0909** [comment]
@congqixia can you pls check it ?

**Comment by congqixia** [comment]
> @congqixia can you pls check it ?

Sure, just checked the code base. It turned out that this unsafe block could be removed.
