### ISSUE TITLE
[Bug]: No error raised when the rootPath is wrong

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/birdwatcher#98]
### Current Behavior

My Milvus is deployed by helm, so the default rootPath is `by-dev`.

But I refer to the following command, set the rootPath as instance name.
![image](https://user-images.githubusercontent.com/12268675/220337871-ae6c256c-980a-4974-878b-dc0e3cd9daf9.png)

However, it does not raise any errors. It can not show any info when I type show collections(already create many collections).

This makes me confused: It does not work, but there is no error happened.the 

### Expected Behavior

Raise an error when the config is wrong.

**Comment by congqixia** [comment]
Good point. Currently `Birdwatcher` cannot detect rootPath was a valid one or not. 
We could add a cheap check at least that whether rootPath prefix exists or not

**Comment by congqixia** [comment]
Pr merged. Could you please check?
/assign @zhuwenxing 
/unassign
